version: "3.9"

services:
  nb-editor:
      build:
        context: .
      image: nb-editor
      container_name: nb-editor
      volumes:
        - ./runtime/static:/app/packages/server/static
      expose:
        - '5001-5003'
      ports:
        - '5001-5003:5001-5003'
      depends_on:
        - db
        - redis
  db:
    restart: always
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: editor
    volumes:
      - data:/var/lib/postgres/main-data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
  testdb:
    image: postgres:16.3-alpine
    volumes:
      - data:/var/lib/postgres/test-data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: editor_test
    ports:
      - 5480:5432
  redis:
    image: redis:7.4.0-alpine
    restart: always
    volumes:
      - data:/var/lib/redis
    ports:
      - 6379:6379
  testRedis:
    image: redis:7.4.0-alpine
    volumes:
      - data:/var/lib/test-redis
    ports:
      - 6380:6379

volumes:
  data:
    driver: local