import { Providers } from '@/components/layout/providers';
import { checkIsLogin } from '@/libs/auth';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  unauthorized,
  authorized
}: Readonly<{
  unauthorized: React.ReactNode;
  authorized: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body id="__next" className={inter.className}>
        <Providers>
          {(await checkIsLogin()) ? authorized : unauthorized}
        </Providers>
      </body>
    </html>
  );
}
